jsoup:
  user-agent: HedgehogSearchBot
  referrer: http://www.google.com

indexing-settings:
  sites:
#    - url: https://lenta.ru/
#      name: Лента.ру
    - url: https://skillbox.ru/
      name: Skillbox

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: root
    password: 1azX2sxC3dcV12/*
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
